### ISSUE TITLE
dalao能教教怎么使用吗

### ISSUE THREAD

**Issue by woaiyouxi0803** [alibaba/virtualview_tools#10]
=========================TemplateWorkSpace =========================
sh buildTemplate.sh
java.io.FileNotFoundException: /virtualview_tools-master/compiler-tools/TemplateWorkSpace/templatelist.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at com.libra.virtualview.tool.CompilerResourceConfig.<init>(CompilerResourceConfig.java:55)
	at com.libra.virtualview.tool.VirtualViewCompileTool.compileInProject(VirtualViewCompileTool.java:71)
	at com.libra.virtualview.tool.VirtualViewCompileTool.main(VirtualViewCompileTool.java:44)
templatelist.properties path error!
templatelist.properties path error!

========================= RealtimePreview=========================
./run.sh
############# Build: out files #############
java.io.FileNotFoundException:/virtualview_tools-master/compiler-tools/RealtimePreview/templatelist.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at com.libra.virtualview.tool.CompilerResourceConfig.<init>(CompilerResourceConfig.java:55)
	at com.libra.virtualview.tool.VirtualViewCompileTool.compileInProject(VirtualViewCompileTool.java:71)
	at com.libra.virtualview.tool.VirtualViewCompileTool.main(VirtualViewCompileTool.java:44)
templatelist.properties path error!
templatelist.properties path error!
############# Build: data.json #############
模版 .out 未找到 : HelloWorld.xml
############# Run HTTP Server #############
Start HTTP Server : http://192.168.0.113:7788
############# Dir #############
templates: ["HelloWorld"]

**Comment by isaced** [comment]
如果是想要 RealtimePreview 的话，直接切到 RealtimePreview 目录即可；不需要先到 TemplateWorkSpace 执行 buildTemplate.sh。

排查的话可以尝试把 run.sh 中的 clean 先注释掉，然后执行一次看看  templatelist.properties 文件生成成功没有，看看具体原因。

**Comment by woaiyouxi0803** [comment]
└── templates (按文件夹分割存放模版)
    └── helloworld
        ├── helloworld.json   (该模版所需参数)
        ├── helloworld.out    (该模版编译后的二进制)
        ├── helloworld.xml    (该模版源文件)
        └── helloworld_QR.png (该模版 URL 供于扫码加载)

上面文件夹内有data.json，HelloWorld.json，HelloWorld.xml

可能是我环境不对。macOS上的java10.0.1
TemplateWorkSpace 执行sh buildTemplate.sh 会是的第一个。

注释后 run.sh 会生成templatelist.properties（内容HelloWorld=HelloWorld,1530079137）和  文件夹template（里面是HelloWorld.xml）
提示 templatelist.properties path error!

**Comment by isaced** [comment]
@woaiyouxi0803 大兄弟，实时预览工具已经用 Ruby 重写更新了，
